# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mchuv\Docs\DataProtection\Lab06\ui\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(480, 496)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.usersTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.usersTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.usersTableWidget.setColumnCount(3)
        self.usersTableWidget.setObjectName("usersTableWidget")
        self.usersTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.usersTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.usersTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.usersTableWidget.setHorizontalHeaderItem(2, item)
        self.usersTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.usersTableWidget.horizontalHeader().setHighlightSections(True)
        self.usersTableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.usersTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.usersTableWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newUserLoginLabel = QtWidgets.QLabel(self.centralwidget)
        self.newUserLoginLabel.setObjectName("newUserLoginLabel")
        self.horizontalLayout.addWidget(self.newUserLoginLabel)
        self.newUserLoginEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newUserLoginEdit.setObjectName("newUserLoginEdit")
        self.horizontalLayout.addWidget(self.newUserLoginEdit)
        self.addNewUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewUserButton.setObjectName("addNewUserButton")
        self.horizontalLayout.addWidget(self.addNewUserButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(AdminWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(AdminWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionChange_password = QtWidgets.QAction(AdminWindow)
        self.actionChange_password.setObjectName("actionChange_password")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionChange_password)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Admin"))
        item = self.usersTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AdminWindow", "User"))
        item = self.usersTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AdminWindow", "Blocked"))
        item = self.usersTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AdminWindow", "Restriction"))
        self.newUserLoginLabel.setText(_translate("AdminWindow", "New User Login"))
        self.addNewUserButton.setText(_translate("AdminWindow", "Add"))
        self.menuFile.setTitle(_translate("AdminWindow", "F&ile"))
        self.menuHelp.setTitle(_translate("AdminWindow", "H&elp"))
        self.actionExit.setText(_translate("AdminWindow", "&Exit"))
        self.actionAbout.setText(_translate("AdminWindow", "&About"))
        self.actionChange_password.setText(_translate("AdminWindow", "&Change password"))
