# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\newUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newUserDialog(object):
    def setupUi(self, newUserDialog):
        newUserDialog.setObjectName("newUserDialog")
        newUserDialog.setWindowModality(QtCore.Qt.WindowModal)
        newUserDialog.resize(399, 135)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newUserDialog.sizePolicy().hasHeightForWidth())
        newUserDialog.setSizePolicy(sizePolicy)
        newUserDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(newUserDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newUserLoginLabel = QtWidgets.QLabel(newUserDialog)
        self.newUserLoginLabel.setObjectName("newUserLoginLabel")
        self.horizontalLayout.addWidget(self.newUserLoginLabel)
        self.newUserLoginEdit = QtWidgets.QLineEdit(newUserDialog)
        self.newUserLoginEdit.setObjectName("newUserLoginEdit")
        self.horizontalLayout.addWidget(self.newUserLoginEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(newUserDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(newUserDialog)
        self.buttonBox.accepted.connect(newUserDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(newUserDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newUserDialog)

    def retranslateUi(self, newUserDialog):
        _translate = QtCore.QCoreApplication.translate
        newUserDialog.setWindowTitle(_translate("newUserDialog", "New User"))
        self.newUserLoginLabel.setText(_translate("newUserDialog", "New User Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newUserDialog = QtWidgets.QDialog()
    ui = Ui_newUserDialog()
    ui.setupUi(newUserDialog)
    newUserDialog.show()
    sys.exit(app.exec_())
