# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mchuv\Docs\DataProtection\Lab06\installer\src\ui\searchFolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectFolderDialog(object):
    def setupUi(self, selectFolderDialog):
        selectFolderDialog.setObjectName("selectFolderDialog")
        selectFolderDialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(14)
        selectFolderDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(selectFolderDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.searchFolderButton = QtWidgets.QPushButton(selectFolderDialog)
        self.searchFolderButton.setObjectName("searchFolderButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.searchFolderButton)
        self.destDirLabel = QtWidgets.QLabel(selectFolderDialog)
        self.destDirLabel.setText("")
        self.destDirLabel.setObjectName("destDirLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.destDirLabel)
        self.label = QtWidgets.QLabel(selectFolderDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.regPartLineEdit = QtWidgets.QLineEdit(selectFolderDialog)
        self.regPartLineEdit.setObjectName("regPartLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.regPartLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(selectFolderDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(selectFolderDialog)
        self.buttonBox.accepted.connect(selectFolderDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(selectFolderDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(selectFolderDialog)

    def retranslateUi(self, selectFolderDialog):
        _translate = QtCore.QCoreApplication.translate
        selectFolderDialog.setWindowTitle(_translate("selectFolderDialog", "Установщик"))
        self.searchFolderButton.setText(_translate("selectFolderDialog", "Search Folder"))
        self.label.setText(_translate("selectFolderDialog", "Reg key"))
